# Generated by Django 3.0.4 on 2020-04-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
    ]
