# Generated by Django 3.0.4 on 2020-04-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='hostel_name',
        ),
    ]
