# Generated by Django 3.0.4 on 2020-04-11 18:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200411_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
