# Generated by Django 2.0 on 2020-04-14 08:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_post_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="contact",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, unique=True
            ),
        ),
    ]
