# Generated by Django 3.0.4 on 2020-04-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_auto_20200412_2208"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomcategory",
            name="price",
            field=models.DecimalField(decimal_places=4, default=50000.0, max_digits=12),
        ),
    ]
