# Generated by Django 3.0.4 on 2020-04-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_auto_20200414_1348"),
        ("blog", "0011_auto_20200414_1102"),
    ]

    operations = []
