# Generated by Django 3.0.4 on 2020-04-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200414_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='id',
            field=models.IntegerField(default=196, primary_key=True, serialize=False),
        ),
    ]
